#!/usr/bin/perl
# Perl v5.36.0 on macOS Ventura 13.0.1
# Learning Perl 8th Edition
# Author: Ronald Rios
# Chapter 13: Directory operations
# Exercise 4: rm

use feature 'say';
use warnings;
use strict;

say 'Exercise 13.4';

foreach (@ARGV){
    unlink $_ or warn "Can't unlink $_: $!"
}

